### ISSUE TITLE
Composer (SSH Access as a requirement)

### ISSUE THREAD

**Issue by danieljharrin** [anchorcms/anchor-docs#29]
Hi all,

Browsing through the install docs and see no mention of SSH access (for Composer), as a requirement.

Some people hosting on shared servers might not have SSH access and are wondering why when they upload the files and navigate to /install there is a 500 error, not even a warning.

Shouldn't this be a priority to add to the docs?

Daniel

**Comment by CraigChilds94** [comment]
@danieljharrin 

How you connect to a hosting provider varies greatly depending on the service, we'll probably just add a statement for people to refer to their hosting providers documentation.

Also, we should be supplying packaged versions with the composer process already run, this will save users from having to complete this task.

If you don't have ssh access to the server then it's best to run it locally and upload the `vendor` folder to the server, I hope this helps :)
