### ISSUE TITLE
Question: How to create a script to process post data

### ISSUE THREAD

**Issue by davidapple** [anchorcms/anchor-docs#34]
Apologies if this is an amateur question.

I'm building an Anchor theme. I want to collect data from visitors.

```
<form action="/subscribe" method="post">
  <input type="text" name="email">
  <input type="submit">
</form>
```

How do I create a page that handles the post data?

```
<?php
echo $_POST["email"];
?>
```

Simply creating new page templates returns a 500 error. It seems to cause a problem with the router. How do I create pages that handle post data?

**Comment by daviddarnes** [comment]
If I were you @davidapple I would use another service other than Anchor to handle users data. The admin interface won't be able to present the data correctly. Maybe [Mailchimp](https://mailchimp.com/) is more suited for this? Or [Formspree](https://formspree.io/)?

**Comment by daviddarnes** [comment]
Closing this as I think we’ve adequately answered the question
